# Site settings
title: SustainFund
email: markbruns@markbruns.com
description: Zero Donor Support. Zero Fundraising. Zero Overhead Philanthropy. BE a human. BE a problem solver. EMBODY genuine compassion. Give yourself.
twitter_username: MarkBruns
github_username:  sustainfund

# Build settings
markdown: kramdown